sudo: required

services: docker
language: python

python: 2.7

env:
  global:
   - secure: "l/LL3x3wrbjF03CxqexVVqZqTCfLgJBOa68BS1Aoc5tfClxPtrEorNGfSn2IiD+xCTz9DOiWClNaUdacUePXDuoWE1oi7QWrRyPfYOaYGWAmSfab5uQK0NV7ZglaiYpeO3JjDnqeBr0pHCpEgUd2SpbWbWL64CMXQQrPkUiOUzkl/QSFB1bAMWYL/vpSAfZO68s8dceKwRNXQ48cocVbt9zbio0RD6W4uHrZLYysGFXtBO4pW3uhRgNz1v9Mw6n2/8noez5dO80YG4fjF7/OHNS7IGvhriqbPmYJthsTLwJ97TsEz2R85p/2lO8z8Af4vIvo3UOHyOfk+bUjZoq8tj6JeSNEbk/8P1DKduvF5rrQ5JZniF+4/RApSntRIaAkYcKWLyHdWh9bev9oH+9CPTYYhmJkQMSZDX+bSpBkFmREzzZ/x3rYwkqS3fxBlfEEu5sUrzcpN9i8xLNBxG+x2gAqhVZ2N/Ik9/wq0UNKJ4o0UocH3+RKjvHUofpqo9BKI2fvKjP+09FgctQMqSRPw9+vX4HRzGnKDZfSINddw1GkdbCko/huMtVUMTeafd6FzKj1vvDvPMlsdufTqkUagreVl6qlncXvPgYdjoHnrxhncMKrAmsE4ME9B4bGlhv+HdnOgEH20hbLx02qIbpgY6vxO4jLZ84db/BpbJzBQNU="
  matrix:
   - DISTRIB=xenial PYTHON_VERSION=2
   - DISTRIB=trusty PYTHON_VERSION=2
   - DISTRIB=precise PYTHON_VERSION=2
   - DISTRIB=stretch PYTHON_VERSION=2
   - DISTRIB=wheezy PYTHON_VERSION=2
   - DISTRIB=jessie PYTHON_VERSION=2
   - DISTRIB=docker PYTHON_VERSION=2
   - DISTRIB=xenial PYTHON_VERSION=3
   - DISTRIB=stretch PYTHON_VERSION=3
   - DISTRIB=trusty PYTHON_VERSION=3
   - DISTRIB=jessie PYTHON_VERSION=3
   - DISTRIB=docker PYTHON_VERSION=3

before_install:
- pip install coveralls
- /bin/bash travis_run.sh $DISTRIB before_install $PYTHON_VERSION $PASSWORD

install:
- /bin/bash travis_run.sh $DISTRIB install $PYTHON_VERSION

script:
- /bin/bash travis_run.sh $DISTRIB script $PYTHON_VERSION

after_script:
- /bin/bash travis_run.sh $DISTRIB after_script $PYTHON_VERSION
