language: python
python: 2.7

before_install:
  - sudo apt-get -qq update
  - bash scripts/build_dep_ubuntu1204

install:
  - bash scripts/make
  - bash scripts/configure_apache_ubuntu1204
  - bash scripts/install_apache_ubuntu1204


script:
  - bash scripts/test_apache
