language: python
python: 2.7

before_install:
  - sudo apt-get -qq update
  -	chmod +x scripts/*
  - scripts/build_dep

install:
  - scripts/make
  - scripts/configure_apache
  - scripts/install_apache


script:
  - ./scripts/test_apache
