sudo: required

services: docker

language: python

python: 2.7

env:
  - DISTRIB=xenial
  - DISTRIB=trusty
  - DISTRIB=precise
  - DISTRIB=stretch
  - DISTRIB=wheezy
  - DISTRIB=jessie

before_install:
- pip install coveralls
- docker pull signetsim/signetsim:$DISTRIB

install:
- docker run -di --name test_env -v $(pwd):/home/travis/build/vincent-noel/SigNetSim signetsim/signetsim:$DISTRIB bash
- docker exec test_env /bin/bash /home/travis/build/vincent-noel/SigNetSim/scripts/install.sh

script:
- docker exec test_env su - www-data -s /bin/bash /home/travis/build/vincent-noel/SigNetSim/scripts/test_apache.sh
- docker exec test_env su - www-data -s /bin/bash /home/travis/build/vincent-noel/SigNetSim/scripts/run_tests.sh

after_script:
- coveralls
