sudo: required

services: docker

language: python

python: 2.7

env:
  - DISTRIB=xenial
  - DISTRIB=trusty
  - DISTRIB=precise
  - DISTRIB=wheezy
  - DISTRIB=jessie
  - DISTRIB=stretch


before_install:
- pip install coveralls
- docker pull signetsim/signetsim:$DISTRIB

install:
- docker run -di --name test_env -v $(pwd):/home/travis/build/vincent-noel/SigNetSim signetsim/signetsim:$DISTRIB bash
- docker exec test_env /bin/bash -c "cd /home/travis/build/vincent-noel/SigNetSim; bash scripts/$DISTRIB/install.sh"
- docker exec test_env /bin/bash -c "cd /home/travis/build/vincent-noel/SigNetSim; bash scripts/apache/generate_apache.sh"
- docker exec test_env /bin/bash -c "cd /home/travis/build/vincent-noel/SigNetSim; bash scripts/apache/install_apache.sh"
- docker exec test_env /bin/bash -c "cd /home/travis/build/vincent-noel/SigNetSim; bash scripts/create_db.sh"


script:
- docker exec test_env /bin/bash -c "cd /home/travis/build/vincent-noel/SigNetSim; bash scripts/test_apache.sh"
- docker exec test_env /bin/bash -c "cd /home/travis/build/vincent-noel/SigNetSim; bash scripts/run_tests.sh"

after_script:
- coveralls
