language: python
python: 2.7

before_install:
  - sudo apt-get -qq update
  - bash scripts/build_dep_debian

install:
  - bash scripts/make
  - bash scripts/configure_apache
  - bash scripts/install_apache


script:
  - bash scripts/test_apache
