sudo: required

services: docker

language: python

python: 2.7

before_install:
- pip install coveralls
- docker pull signetsim/signetsim:xenial

install:
- docker run -di --name test_env -v $(pwd):/home/travis/build/vincent-noel/libSigNetSim signetsim/signetsim:xenial bash
- docker exec test_env /bin/bash -c "cd /home/travis/build/vincent-noel/SigNetSim; bash scripts/install.sh"
