#docker-compose.yml
version: '3.3'
services:
  signetsim-py2:
    build:
      context: ./
      dockerfile: scripts/docker-py2/Dockerfile
    image: signetsim/signetsim:develop-py2
    container_name: signetsim-py2
    volumes:
      - signetsim_data:/SigNetSim/data
    ports:
      - "8080:80"
    restart: always

  signetsim:
    build:
      context: ./
      dockerfile: scripts/docker-py3/Dockerfile
    image: signetsim/signetsim:develop
    container_name: signetsim
    volumes:
      - signetsim_data:/SigNetSim/data
    ports:
      - "8080:80"
    restart: always

volumes:
  signetsim_data:
